config-version = "2.7"
bind = "0.0.0.0:25565"
motd = "&3A Velocity Proxy"
show-max-players = 500
online-mode = true
prevent-client-proxy-connections = false
# legacy is required for Vanilla servers that don't support modern forwarding
player-info-forwarding-mode = "modern"
forwarding-secret-file = "forwarding.secret"
announce-forge = false
kick-existing-players = false
force-key-authentication = false
ping-passthrough = "MODS"

[servers]
lobby = "127.0.0.1:25566"
try = ["lobby"]

[forced-hosts]
